# Sets the relation of branches in current repository with
# source repositories branches

maintenance_6.2:
- repo: rancher/elemental-toolkit
  branch: v2.3.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-operator
  branch: v1.8.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental
  branch: v2.3.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-channels
  branch: v1.8
  parseVersion: none
  versionOffset: no

maintenance_6.1:
- repo: rancher/elemental-toolkit
  branch: v2.2.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-operator
  branch: v1.7.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental
  branch: v2.2.x
  parseVersion: patch
  versionOffset: no
- repo: rancher-sandbox/cluster-api-provider-elemental
  branch: main
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-channels
  branch: v1.7
  parseVersion: none
  versionOffset: no
